name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: TeuzLins
          outputs: |
            dist/github-snake.svg?color_snake=%2370A5FD&color_dots=%230D1117,%231A1B27,%233B4261,%2370A5FD,%23BF91F3
            dist/github-snake-dark.svg?color_snake=%23BF91F3&color_dots=%230D1117,%231A1B27,%233B4261,%2370A5FD,%23BF91F3

      - name: Publish contribution snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
